parameters:
  name: ""

jobs:
- job: TestRole_${{ parameters.name }}
  displayName: Test Role ${{ parameters.name }}
  pool:
    vmImage: "ubuntu-16.04"
  timeoutInMinutes: 60
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.6"
      addToPath: true
      architecture: "x64"

  - script: |
      python -m pip install --upgrade pipenv
      pipenv sync -d
    displayName: "SETUP: Install dependencies"
    condition: succeeded()

  - script: |
      cd roles/${{ parameters.name }}
      pipenv run molecule test --all
    displayName: "TEST: Run all scenarios"
    condition: succeeded()
