---
# defaults file for core
common_realname: "Admin user"
common_username: "{{ lookup('env', 'USER') | default('jlrickert') }}"
common_additional_packages: []
common_ssh_keys: []
common_domain_name: "example.com"
common_local_domain_name: "example.local"