---
- name: Remove old jlrickert.me
  file:
    path: "{{ jlrickert_me.directory }}"
    state: absent
  tags:
    - jlrickert.me

- name: Clone jlrickert.me
  git:
    repo: "https://github.com/jlrickert/jlrickert.github.io"
    dest: "{{ jlrickert_me.directory }}"
    update: yes
  become: yes
  tags:
    - jlrickert.me

- name: Create jlrickert.me log directory
  file:
    path: "{{ nginx.log }}/jlrickert.me"
    state: directory
  tags:
    - jlrickert.me

- name: Push jlrickert.me to nginx config
  template:
    src: jlrickert.me.j2
    dest: /etc/nginx/sites-available/jlrickert.me
  notify:
    - restart nginx
  tags:
    - jlrickert.me

- name: Enable jlrickert.me reverse proxy
  file:
    src: /etc/nginx/sites-available/jlrickert.me
    dest: /etc/nginx/sites-enabled/jlrickert.me
    state: link
  notify:
    - restart nginx
  tags:
    - jlrickert.me
