---
- name: Install packages (Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: [
      "aptitude",
      "fasd",
      "git",
      "htop",
      "lsof",
      "silversearcher-ag",
      "ssh",
      "tree",
      "vim",
      "zsh"
    ]
    state: present
  register: ubuntu_packages

- name: Install additional packages (Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ ubuntu_additional_packages }}"
    state: present

- name: Get zsh shell location
  command: which zsh
  changed_when: no
  failed_when: zsh_path_res.rc != 0
  register: zsh_path_res

- name: "Create user {{ username }}"
  user:
    name: "{{ username }}"
    state: present
    comment: "Admin user"
    groups:
      - "sudo"
    shell: "{{ zsh_path_res.stdout }}"
    create_home: yes
    append: yes

- name: Copy sudoers config
  become: yes
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: "0440"
    validate: "visudo -cf %s"

- name: Make SSH directory for user
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Set authorization keys for {{ username }}
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ item }}"
  loop: "{{ ssh_keys }}"

- name: Docker hack so sshd config may be tested
  become: yes
  when: ansible_hostname == "instance"
  file:
    path: "/run/sshd"
    state: directory

- name: Copy sshd configuration
  become: yes
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: Enable and start SSH Daemon
  when: ansible_hostname != "instance"
  service:
    name: sshd.service
    enabled: yes
    state: started

- name: Install oh my zsh for {{ username }}
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "~/.oh-my-zsh"
    update: yes
    version: master

- name: Install chezmoi binary
  apt:
    deb: https://github.com/twpayne/chezmoi/releases/download/v1.6.5/chezmoi_1.6.5-1226_linux_amd64.deb
    state: present

- name: "Create chezmoi config directory for {{ username }}"
  file:
    path: "/home/{{ username }}/.config/chezmoi"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install chezmoi config
  template:
    src: chezmoi.toml.j2
    dest: "/home/{{ username }}/.config/chezmoi/chezmoi.toml"
    owner: "{{ username }}"
    group: "{{ username }}"
  register: chezmoi_res

- name: Update dotfiles
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/jlrickert/dotfiles.git
    dest: "~/.local/share/chezmoi"
    update: yes
    version: master

- name: Keep chezmoi from complaining about "~/.local/share/chezmoi" not being private
  become: yes
  become_user: "{{ username }}"
  file:
    path: ~/.local/share/chezmoi
    state: directory
    mode: "0700"

- name: Apply chezmoi magic
  become: yes
  become_user: "{{ username }}"
  changed_when: chezmoi_res.rc != 0
  command: chezmoi apply
  register: chezmoi_res
