---
- import_tasks: i3.yml
  tags:
      - i3

- import_tasks: syncthing.yml
  tags:
      - syncthing

- import_tasks: packages.yml
  tags:
      - packages

- import_tasks: ufw.yml
  tags:
      - ufw

- import_tasks: ssh_config.yml
  tags:
      - ssh_config
