---
- name: Install i3 packages (Debian)
  when: ansible_os_family == "Debian"
  apt:
    name: [
      "arandr",
      "i3",
      "xsel",
      "xclip",
      "rxvt-unicode"
    ]
    state: present

- name: Enable syncthing through firewall
  ufw:
    name: syncthing
    rule: allow
  tags:
    - syncthing

- name: Install External debian packages
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
    - "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
    - "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    - "https://go.microsoft.com/fwlink/?LinkID=760868"
    - "https://discordapp.com/api/download?platform=linux&format=deb"
    - "https://download.notable.md/?target=deb"
