---
- name: Deny incoming traffic by default
  ufw:
      default: deny
      direction: incoming
  tags:
      - ufw

- name: Allow outgoing traffic by default
  ufw:
      default: allow
      direction: outgoing
  tags:
      - ufw
