---
- name: Download Go tarball
  get_url:
      url: "https://golang.org/dl/{{ go_tarball }}"
      dest: /usr/local/src/{{ go_tarball}}
      checksum: "{{ go_checksum }}"

- name: Register current Go version (if any)
  command: /usr/local/share/go/bin/go version
  ignore_errors: yes
  failed_when: false
  changed_when: false
  register: go_version

- name: Remove old installation of go
  file:
      path: /usr/local/share/go
      state: absent
  when: go_version.stdout != go_version_check

- name: Create go root directory
  file:
      path: /usr/local/share/go
      state: directory

- name: Extract Go tarball
  unarchive:
      src: "/usr/local/src/{{ go_tarball }}"
      dest: /usr/local/share
      copy: no
  when: go_version is failed or go_version.stdout != go_version_check

- name: Set default golang variables for all users
  copy:
      src: golang.sh
      dest: /etc/profile.d/golang.sh

- name: Create /usr/local/bin directory
  file:
      path: /usr/local/bin
      state: directory

- name: Link go binary to /usr/local/bin/go
  file:
      src: /usr/local/share/go/bin/go
      dest: /usr/local/bin/go
      state: link
