---
- name: Ensure apt-transport-https is installed.
  apt:
    name: apt-transport-https
    state: present

- import_tasks: nodejs.yml
  tags:
    - nodejs

- import_tasks: java.yml
  tags:
    - java

# - import_tasks: scala.yml
#   tags:
#     - scala

- import_tasks: python.yml
  when: "python_install and ansible_distribution_release == 'bionic'"
  tags:
    - python

- import_tasks: golang.yml
  tags:
    - golang
