---
- name: Ensure apt-transport-https is installed.
  apt:
    name: apt-transport-https
    state: present

- name: Import nodejs language role
  import_tasks: nodejs.yml
  tags:
    - nodejs

- name: Import java language role
  import_tasks: java.yml
  tags:
    - java

# - import_tasks: scala.yml
#   tags:
#     - scala

- name: Import python language role
  import_tasks: python.yml
  tags:
    - python

- name: Import golang language role
  import_tasks: golang.yml
  tags:
    - golang
