---
- name: "Get environmental variables for {{ common_username }}"
  become: yes
  become_user: "{{ common_username }}"
  command: "ssh {{ inventory_hostname | quote }} echo $NVM_DIR"
  delegate_to: localhost
  changed_when: false
  register: nvm_dir_res

- name: Fetch nvm tag information
  uri:
    url: https://api.github.com/repos/nvm-sh/nvm/tags
    headers:
      Accept: "application/vnd.github.v3+json"
    return_content: yes
  register: nvm_repo_tag_res

- name: "Query nvm tag information for latest version"
  set_fact:
    nodejs_nvm_version: "{{ nvm_repo_tag_res.json | map(attribute='name') | list | first }}"

- name: Install nvm
  become: yes
  become_user: "{{ common_username }}"
  git:
    repo: https://github.com/nvm-sh/nvm.git   
    dest: "{{ nvm_dir_res.stdout | default('~/.nvm') }}"
    version: "{{ nodejs_nvm_version }}"
