---
- name: Add bintray apt key.
  apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823
      id: "99E82A75642AC823"

- name: Add bintray repositories for sbt.
  apt_repository:
      repo: "{{ item }}"
      state: present
  with_items:
      - "deb [arch=amd64] https://dl.bintray.com/sbt/debian /"
  notify: update cache

- name: Ensure sbt is installed
  apt:
      name: "sbt={{ scala_version|regex_replace('x', '') }}*"
      state: present
