---
- name: add deploy user
  user:
    name: "deploy"
    createhome: "yes"
  tags:
    - git-remote

- name: Make SSH directory for user
  file:
    path: "/home/git/.ssh"
    state: directory
    mode: 0700
    owner: "{{ ansible_user }}"
    group: users
  tags:
    - git-remote

- name: Setup authorization key for user
  authorized_key:
    user: "deploy"
    state: present
    key: "{{ lookup('file', '/home/{user}/.ssh/id_rsa_{user}.pub'.format(user=ansible_user)) }}"
  tags:
    - git-remote
