---
# handlers file for core
- name: restart sshd
  when: ansible_hostname != "instance"
  service:
      name: sshd.service
      state: restarted

- name: restart ufw
  service:
      name: ufw.service
      state: restarted
