---
- name: reload systemd config
  command: systemctl daemon-reload

- name: restart sshd
  service:
    name: sshd.socket
    state: restarted

- name: reset kernel parameters
  command: sysctl --system
