---
- name: Install apache-tools dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - pcre
    - apr-util
  tags:
    - aur
    - auth

- name: Install apache-tools for htpasswd
  aur:
    name: apache-tools
    user: "{{ ansible_user }}"
    dir: /tmp
  tags:
    - aur
    - auth

- name: Create auth folder
  file:
    path: /etc/auth
    state: directory
  tags:
    - auth

- name: Create htpasswd file
  file:
    path: /etc/auth/htpasswd
    state: touch
  tags:
    - auth
