---
- name: clone user dotfiles
  git:
    repo={{ dotfiles.url }}
    dest=/home/{{ ansible_user }}/dotfiles
    update=yes
  become: yes
  become_user: "{{ ansible_user }}"

- name: Install dotfiles
  command: python /home/{{ ansible_user }}/dotfiles/install.py other
  become: yes
  become_user: "{{ ansible_user }}"
