---
- import_tasks: common.yml
  tags:
    - common

- import_tasks: packages.yml
  tags:
    - common
    - packages

- import_tasks: user.yml
  tags:
    - common
    - user

- import_tasks: dotfiles.yml
  tags:
    - common
    - user
    - dotfiles

- import_tasks: ssh.yml
  tags:
    - common
    - ssh

- import_tasks: hostnames.yml
  tags:
    - common
    - hostnames
