---
- import_tasks: packages.yml
  tags:
      - packages

- import_tasks: sudo.yml
  tags:
      - sudo

# - import_tasks: hostnames.yml
#   tags:
#     - hostnames

- import_tasks: ssh.yml
  tags:
      - ssh

- import_tasks: user.yml
  tags:
      - user

- import_tasks: ufw.yml
  tags:
      - ufw
