---
- name: Install packages (Debian)
  when: ansible_os_family == "Debian"
  apt:
    name: [
      "apt-file",
      "aptitude",
      "command-not-found",
      "curl",
      "fasd",
      "git",
      "htop",
      "lsof",
      "silversearcher-ag",
      "ssh",
      "tree",
      "wget",
      "zsh"
    ]
    state: present
  register: debian_packages

- name: Install additional packages (Debian)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ common_additional_packages }}"
    state: present
