---
- name: Enable non free software
  when: ansible_os_family == "Debian"
  template:
      src: sources.list.j2
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: "0644"
  register: source_list

- name: Update repository
  when: source_list.changed
  apt:
      update_cache: yes

- name: Install packages (Debian)
  when: ansible_os_family == "Debian"
  apt:
      name:
          [
              "ansible",
              "apt-file",
              "aptitude",
              "command-not-found",
              "curl",
              "dnsutils",
              "fasd",
              "fonts-noto-color-emoji",
              "git",
              "htop",
              "httpie",
              "lsof",
              "nmap",
              "python-apt",
              "python3-apt",
              "silversearcher-ag",
              "ssh",
              "tree",
              "wget",
              "zsh",
          ]
      state: present

- name: Install additional group packages
  when: ansible_os_family == "Debian"
  apt:
      name: "{{ group_packages }}"
      state: present

- name: Install additional host packages
  when: ansible_os_family == "Debian"
  apt:
      name: "{{ host_packages }}"
      state: present
