---
- name: Install packages (Debian)
  when: ansible_os_family == "Debian"
  apt:
    name: [
      "ansible",
      "apt-file",
      "aptitude",
      "command-not-found",
      "curl",
      "dnsutils",
      "fasd",
      "git",
      "htop",
      "httpie",
      "lsof",
      "nmap",
      "python-apt",
      "python3-apt",
      "silversearcher-ag",
      "ssh",
      "tree",
      "wget",
      "zsh"
    ]
    state: present

- name: Install additional packages
  apt:
    name: "{{ common_additional_packages }}"
    state: present
