---
- name: Install OpenSSH
  apt:
    name: ssh
    update_cache: yes
  when: ansible_facts["os_family"] == "Debian"

- name: Install OpenSSH
  pacman:
    name: openssh
    state: present
  when: ansible_facts["os_family"] == "Archlinux"
