---
- include: ssh-debian.yml
  when: ansible_os_family == "Debian"

- include: ssh-arch.yml
  when: ansible_os_family == "Archlinux"

- name: Make SSH directory for user
  file:
    path: "/home/{{ common_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ common_user }}"
    group: users

- name: Set authorization key for {{ common_user }}
  authorized_key:
    user: "{{ common_user }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Copy sshd configuration
  become: true
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: Enable and start SSH Daemon
  service:
    name: sshd.service
    enabled: yes
    state: started
