---
- name: Install OpenSSH (Debian)
  apt:
    name: ssh
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install OpenSSH (Arch)
  pacman:
    name: openssh
    state: present
  when: ansible_os_family == "Archlinux"


- name: Make SSH directory for user
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ username }}"
    group: users

- name: Set authorization key for {{ username }}
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Copy sshd configuration
  become: true
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: Enable and start SSH Daemon
  service:
    name: sshd.service
    enabled: yes
    state: started
