---
- name: Install sudo packages
  when: ansible_os_family == "Debian"
  apt:
      name: sudo
      state: present

- name: Find visudo executable
  command: which visudo
  changed_when: False
  register: visudo_exe

- name: Copy sudoers config
  template:
      src: sudoers.j2
      dest: /etc/sudoers
      mode: "0440"
      validate: "{{ visudo_exe.stdout }} -cf %s"
