---
- name: Install sudo packages
  when: ansible_os_family == "Debian"
  apt:
    name: sudo
    state: present

- name: Copy sudoers config
  become: yes
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: "0440"
    validate: "visudo -cf %s"
