---
- name: Install ufw
  apt:
      name: ["ufw"]
      state: present

- name: Enable ufw
  become: yes
  ufw:
      state: enabled

# - name: Deny incoming traffic by default
#   ufw:
#     default: deny
#     direction: incoming

# - name: Allow outgoing traffic by default
#   ufw:
#     default: allow
#     direction: outgoing

- name: Enable OpenSSH through firewall
  become: yes
  ufw:
      rule: limit
      port: ssh
      proto: tcp

- name: Enable and start UFW
  become: yes
  service:
      name: ufw.service
      enabled: yes
      state: started
