---
- name: Ensure sudo group exists
  group:
    name: sudo
    state: present

- name: Ensure wheel group exists
  group:
    name: wheel
    state: present

- name: Create user {{ username }} (Arch)
  user:
    name: "{{ username }}"
    state: present
    groups:
      - audio
      - sudo
      - users
      - video
      - wheel
    append: true
  when:
    ansible_os_family == "Archlinux"

- name: Create user {{ username }} (Debian)
  user:
    name: "{{ username }}"
    state: present
    groups:
      - audio
      - cdrom
      - dip
      - floppy
      - netdev
      - plugdev
      - sudo
      - video
    append: true
  when:
    ansible_os_family == "Debian"
