---
- name: Ensure sudo group exists
  group:
    name: sudo
    state: present

- name: Ensure wheel group exists
  group:
    name: wheel
    state: present

- name: Install zsh for default shell (Debian)
  when: ansible_os_family == "Debian"
  apt:
    name: zsh
    state: present

- name: Install zsh for default shell (Arch)
  when: ansible_os_family == "Archlinux"
  pacman:
    name: zsh
    state: present

- name: Get zsh shell location
  command: which zsh
  changed_when: false
  failed_when: zsh_path_res.rc != 0
  register: zsh_path_res

- name: Create user {{ username }}
  user:
    name: "{{ username }}"
    state: present
    groups: "{{ common_user_groups[ansible_os_family] }}"
    append: true
