---
- name: Create user {{ common_user }}
  user:
    name: "{{ common_user }}"
    shell: /bin/zsh
    state: present
    groups:
      - audio
      - video
      - wheel
    append: true
  when:
    ansible_facts["os_family"] == "Archlinux"

- name: Create user {{ common_user }}
  user:
    name: "{{ common_user }}"
    shell: /bin/zsh
    state: present
    groups:
      - audio
      - cdrom
      - dip
      - floppy
      - netdev
      - plugdev
      - sudo
      - video
    append: true
  when:
    ansible_facts["os_family"] == "Debian"