---
awx_image: "awx"
redis_image: "redis"

postgresql_version: "10"
postgresql_image: "postgres:{{postgresql_version}}"

compose_start_containers: true

# Common Docker parameters
awx_task_hostname: awx
awx_web_hostname: awxweb
postgres_data_dir: "~/.awx/pgdocker"
host_port: 80
host_port_ssl: 443
#ssl_certificate=
# Optional key file
#ssl_certificate_key=
docker_compose_dir: "~/.awx/awxcompose"

# Set pg_hostname if you have an external postgres server, otherwise
# a new postgres service will be created
# pg_hostname=postgresql
pg_username: awx
# pg_password should be random 10 character alphanumeric string, when postgresql is running on kubernetes
# NB: it's a limitation of the "official" postgres helm chart
pg_password: awxpass
pg_database: awx
pg_port: 5432
#pg_sslmode=require

# This will create or update a default admin (superuser) account in AWX, if not provided
# then these default values are used
admin_user: admin
admin_password: password

# Whether or not to create preload data for demonstration purposes
create_preload_data: True

# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
secret_key: awxsecret
