---
- include: pkg-debian.yml
  when: ansible_os_family == "Debian"

- include: pkg-arch.yml
  when: ansible_os_family == "Archlinux"

- name: Add user/s to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users | default([]) }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- name: Enable and start Docker
  service:
    name: docker.service
    daemon_reload: yes
    enabled: yes
    state: started
  register: started_docker
