- name: Install fcgiwrap
  pacman:
    name: fcgiwrap
    state: present
  tags:
    - gitweb

- name: Install spawn-fcgi
  pacman:
    name: spawn-fcgi
    state: present
  tags:
    - gitweb

- name: Install perl-cgi
  pacman:
    name: perl-cgi
    state: present
  tags:
    - gitweb

- name: Create git repository directory
  file:
    path: /srv/git
    state: directory
    owner: git
    group: http
    mode: "u+rw,g+rws"
  tags:
    - gitweb

- name: Add user to git group
  user:
    name: "{{ ansible_user }}"
    groups: git
    append: yes
  tags:
    - gitweb

- name: Add http user to git group
  user:
    name: http
    groups: git
    append: yes
  tags:
    - gitweb

- name: Push gitweb config
  copy:
    src: gitweb.conf
    dest: /etc/gitweb.conf
  tags:
    - gitweb

- name: Push fcgiwrap systemd service
  copy:
    src: fcgiwrap.service
    dest: /etc/systemd/system/fcgiwrap.service
  notify:
    - reload systemd config
  tags:
    - gitweb

- name: Start fcgiwrap service
  service:
    name: fcgiwrap.service
    enabled: yes
    state: started
  tags:
    - gitweb

- name: Create git.jlrickert.me log directory
  file:
    path: /var/log/nginx/git.jlrickert.me
    state: directory
  tags:
    - gitweb

- name: Push gitweb to nginx config
  template:
    src: gitweb.j2
    dest: /etc/nginx/sites-available/gitweb
  tags:
    - gitweb

- name: Enable gitweb
  file:
    src: /etc/nginx/sites-available/gitweb
    dest: /etc/nginx/sites-enabled/gitweb
    state: link
  tags:
    - gitweb
