- name: Install nginx
  pacman:
    name: nginx
    state: present

- name: Create http user
  user:
    name: http
    group: http
    shell: /usr/bin/nologin

- name: Add user to http group
  user:
    name: "{{ ansible_user }}"
    groups: http
    append: yes

- name: Create /srv/http directory
  file:
    path: /srv/http
    state: directory
    owner: http
    group: http
    mode: "u+rw,g+rw,o+x,g+s"


- name: Create git repository directory
  file:
    path: /srv/git
    state: directory
    group: http
  tags:
    - gitweb

- name: Create nginx log directory
  file:
    path: "{{ nginx.log }}"
    owner: root
    group: root
    recurse: yes
    state: directory

- name: Create sites-available directory
  file:
    path: /etc/nginx/sites-available
    state: directory
    owner: root
    group: root

- name: Create sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory
    owner: root
    group: root

- name: Create conf.d directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root

- name: Push nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: Push default config
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Push default ssl config
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf

- name: Push default error pages config
  template:
    src: error_pages.j2
    dest: /etc/nginx/conf.d/error_pages

- name: Copy ssl files
  copy:
    src: "/home/{{ ansible_user }}/Sync/secrets/ssl"
    dest: /etc/nginx/ssl/
    directory_mode: yes
