---
- name: Push notes service file
  copy:
    src: notes.service
    dest: /etc/systemcd/system/notes.service
  notify:
    - reload systemd config
    - restart nginx

- name: install pandoc-watch
  get_url:
    repo: "https://github.com/jlrickert/pandoc-watch.git"
    dest: "/tmp/pandoc-watch"
    update: yes

- name: Compile and install pandoc-watch
  command: make PKGBUILD && makepkg -sri
  args:
    chdir: /tmp/pandoc-watch
    creates: /usr/bin/pandoc-watch

- name: Enable and start notes service
  service:
    name: notes.service
    enabled: yes
    state: started
