---
- name: bootstrap awx
  hosts: awx
  tasks:
      - name: Load Docker Role
        become: yes
        import_role:
            name: docker
        tags:
            - docker

      - name: Load awx Role
        become: yes
        become_user: "{{ username }}"
        import_role:
            name: awx
        tags:
            - awx