---
- hosts: all
  become: yes
  tasks:
    - name: Load common role
      vars:
        common_realname: "{{ realname }}"
        common_username: "{{ username }}"
        common_ssh_keys: "{{ ssh_keys }}"
      import_role:
        name: common
      tags:
        - common