---
- hosts: 127.0.0.1
  connection: local
  tasks:
      - name: Load OpenVPN Authority Role
        import_role:
            name: openvpn
            tasks_from: authority
        tags:
            - openvpn_authority

- hosts: openvpn_server
  become: yes
  become_user: root
  tasks:
      - name: Load OpenVPN Server Role
        import_role:
            name: openvpn
            tasks_from: server.yml
        tags:
            - openvpn_server

- hosts: openvpn_client
  become: yes
  become_user: root
  tasks:
  tasks:
      - name: Load OpenVPN Client Role
        import_role:
            name: openvpn
            tasks_from: client.yml
        tags:
            - openvpn_client