---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: Load common role
        import_role:
            name: common
        tags:
            - common

      - name: Load Dotfiles Role
        become: yes
        become_user: "{{ username }}"
        import_role:
            name: dotfiles
        tags:
            - dotfiles

      - name: Load docker role
        import_role:
            name: docker
        tags:
            - docker

- hosts: workstation
  become: yes
  become_user: root
  tasks:
      - name: Load workstation role
        import_role:
            name: workstation
        tags:
            - workstation

      - name: Load language role
        import_role:
            name: language
        tags:
            - language
