---
- hosts: all
  become: yes
  roles:
    - { role: common }
    - { role: docker }

- hosts: workstations
  become: yes
  roles:
    - { role: workstation }

- hosts: kube-cluster
  become: yes
  roles:
    - { role: kubernetes }

- hosts: kube-masters
  become: yes
  roles:
    - { role: kubernetes/master }
  
- hosts: kube-nodes
  become: yes
  roles:
    - { role: kubernetes/node }
