---
- hosts: all
  become: yes
  tasks:
      - name: Load common role
        import_role:
            name: common
        tags:
            - common

      - name: Load Dotfiles Role
        import_role:
            name: dotfiles
        tags:
            - dotfiles

      - name: Load docker role
        import_role:
            name: docker
        tags:
            - docker

- hosts: workstation
  become: yes
  tasks:
      - name: Load workstation role
        import_role:
            name: workstation
        tags:
            - workstation

      - name: Load language role
        import_role:
            name: language
        tags:
            - language
