---
- hosts: workstations
  become: yes
  roles:
    - { role: common, common_role: workstation }
    - { role: workstation }
    - { role: docker, docker_users: [ "{{ username | default('jlrickert') }}" ] }

- hosts: kube-cluster
  become: yes
  roles:
    - { role: common, common_role: server }
    - { role: kubernetes }
    - { role: docker, docker_users: [ "{{ username | default('jlrickert') }}" ] }

- hosts: kube-masters
  become: yes
  roles:
    - { role: kubernetes/master }
  
- hosts: kube-nodes
  become: yes
  roles:
    - { role: kubernetes/node }

