---
- name: Add Syncthing GPG apt Key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Add Syncthing Repository
  apt_repository:
    repo: deb [arch=amd64] http://apt.syncthing.net/ syncthing release
    state: present

- name: Update apt and install syncthing
  apt:
    name: syncthing
    state: present
    update_cache: yes

- name: "Active Syncthing for users: {{ ', '.join(syncthing_users) }}"
  systemd:
    state: started
    enabled: yes
    name: syncthing@{{ item }}.service
  loop: "{{ syncthing_users }}"
