---
- name: Add Syncthing GPG apt Key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Add Syncthing Repository
  apt_repository:
    repo: deb [arch=amd64] http://apt.syncthing.net/ syncthing release
    state: present

- name: Update apt and install Syncthing
  apt:
    name: syncthing
    state: present
    update_cache: yes

- name: "Enable syncthing for user {{ syncthing_user }} "
  when: syncthing_enabled
  systemd:
    name: syncthing@{{ syncthing_user }}
    state: started
    daemon_reload: yes
    enabled: yes
