---
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Load OpenVPN Authority Role
      import_role:
        name: openvpn
        tasks_from: authority
      tags:
        - openvpn
        - openvpn_authority
