---
- hosts: openvpn_server
  become: yes
  tasks:
    - name: Load OpenVPN Server Role
      import_role:
        name: openvpn
        tasks_from: server.yml
      tags:
        - openvpn
        - openvpn_server
