---
- name: "Create {{ openvpn_ca_pki_path }} for ca"
  become: yes
  become_user: "{{ openvpn_ca_pki_user }}"
  run_once: yes
  file:
    path: "{{ openvpn_ca_pki_path }}"
    state: directory
    mode: 0755
    owner: "{{ openvpn_ca_pki_user }}"
    group: "{{ openvpn_ca_pki_user }}"

- name: Download EasyRSA for ca
  become: yes
  become_user: "{{ openvpn_ca_pki_user }}"
  run_once: yes
  unarchive: 
    src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.7/EasyRSA-3.0.7.tgz
    dest: "{{ openvpn_ca_pki_path }}"
    creates: "{{ openvpn_ca_pki_path }}/easyrsa"
    remote_src: yes
    extra_opts:
      - "--strip-components"
      - "1"
  register: easyrsa_download_res

- name: Deploy CA vars configuration
  become: yes
  become_user: "{{ openvpn_ca_pki_user }}"
  run_once: yes
  vars:
    openvpn_common_name: "{{ openvpn_ca_common_name }}"
  template:
    src: easyrsa3_vars.j2
    dest: "{{ openvpn_ca_pki_path }}/vars"

- name: Initialize CA PKI 
  become: yes
  become_user: "{{ openvpn_ca_pki_user }}"
  run_once: yes
  command:
    cmd: ./easyrsa init-pki
    chdir: "{{ openvpn_ca_pki_path }}"
    creates: "{{ openvpn_ca_pki_path }}/pki/private"

- name: Build CA
  become: yes
  become_user: "{{ openvpn_ca_pki_user }}"
  run_once: yes
  command: 
    cmd: ./easyrsa build-ca nopass
    chdir: "{{ openvpn_ca_pki_path }}"
    creates: "{{ openvpn_ca_pki_path }}/pki/private/ca.key"
