---
- name: Install Openvpn
  apt:
    name: openvpn
    state: present

- name: "Create /etc/openvpn"
  file:
    path: "/etc/openvpn"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"

- name: Download EasyRSA on server
  unarchive:
    src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.7/EasyRSA-3.0.7.tgz
    dest: "/etc/openvpn"
    creates: "/etc/openvpn/easyrsa"
    remote_src: yes
    extra_opts:
      - "--strip-components"
      - "1"
    owner: "root"
    group: "root"

- name: Deploy server vars configuration
  template:
    src: easyrsa3_vars.j2
    dest: "/etc/openvpn/easyrsa/vars"

- name: Initialize server PKI 
  command:
    cmd: ./easyrsa init-pki
    chdir: "/etc/openvpn/easyrsa"
    creates: "/etc/openvpn/easyrsa/pki/private"

- name: Create request cert for server
  command:
    cmd: ./easyrsa gen-req server nopass
    chdir: "/etc/openvpn/easyrsa"
    creates: "/etc/openvpn/easyrsa/pki/private/server.key"

- name: Fetch server request certificate
  fetch:
    src: "/etc/openvpn/easyrsa/pki/reqs/server.req"
    dest: "/tmp/prefix-{{ inventory_hostname }}/"
    flat: yes
  register: server_req_fetch_res

- name: Import server request
  become: yes
  become_user: "{{ openvpn_ca_pki_user }}"
  delegate_to: "{{ openvpn_ca_server }}"
  command:
    cmd: "./easyrsa import-req {{ server_req_fetch_res['dest'] }} server"
    chdir: "{{ openvpn_ca_pki_path }}"
    creates: "{{ openvpn_ca_pki_path }}/pki/reqs/server.req"

- name: Sign server request 
  become: yes
  become_user: "{{ openvpn_ca_pki_user }}"
  delegate_to: "{{ openvpn_ca_server }}"
  command:
    cmd: "./easyrsa sign-req server server"
    chdir: "{{ openvpn_ca_pki_path }}"
    creates: "{{ openvpn_ca_pki_path }}/pki/issued/server.crt"

- name: Copy signed certificate
  copy:
    src: "{{ openvpn_ca_pki_path }}/pki/issued/server.crt"
    dest: "/etc/openvpn/server.crt"
    owner: root
    group: root
    mode: 0600

- name: Copy CA certificate
  copy:
    src: "{{ openvpn_ca_pki_path }}/pki/ca.crt"
    dest: "/etc/openvpn/ca.crt"
    owner: root
    group: root
    mode: 0600

- name: "Create a Diffie-Hellman key (FIXME: copy over to /etc/openvpn/dh.pem)"
  command:
    cmd: ./easyrsa gen-dh
    chdir: "/etc/openvpn/easyrsa"
    creates: "/etc/openvpn//easyrsa/pki/dh.pem"
  register: dh_res

# - name: Copy dh.pem

- name: Generate a HMAC signature
  command:
    cmd: openvpn --genkey --secret ta.key
    chdir: "/etc/openvpn"
    creates: "/etc/openvpn/ta.key"
